apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: muict-app-cert
  namespace: fivetuay10bath-app
spec:
  secretName: muict-app-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - muict.app
